# This is a basic workflow to help you get started with Actions

name: Auto Insource

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      external-action:
        type: string 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      temp_branch: "temp-branch-${{ github.run_id }}"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v3
        # with:
        #   path: common

      # - name: Checkout action repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: ${{ inputs.external-action }}
      #     path: external
      
      - name: Run command
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git switch -c ${{ env.temp_branch }}
          cd external-actions
          git clone https://github.com/${{ inputs.external-action }} ${{ inputs.external-action }}
          rm -r ${{ inputs.external-action }}/.git*
          git add --all
          git commit -m "Add external marketplace action"
          git push --set-upstream origin temp-branch

      - name: Create PR
        run: gh pr create --base main --head ${{env.temp_branch}} --title "Merge ${{env.temp_branch}} into main"
        env:
          GH_TOKEN: ${{ github.token }}


