name: Auto Insource Multiple

on:
  workflow_dispatch:
    inputs:
      actions:
        type: string 
  workflow_call:
    inputs:
      actions:
        type: string 
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      temp_branch: "temp-branch-${{ github.run_id }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: echo ${{inputs.actions}}
      - name: Run command
        id: run
        env:
          ACTIONS: ${{ inputs.actions }}
        run: |
          actions_cloned=0
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git switch -c ${{ env.temp_branch }}
          for action in $ACTIONS; do
            echo $action
            if [[ $action == *"@"* ]]; then
              action_name="$(echo $action | cut -d "@" -f 1)"
              version="$(echo $action | cut -d "@" -f 2)"
              # git clone -b ${version} --depth 1 https://github.com/${action_name} external-actions/${action_name}
            else
              action_name=$action
              version="HEAD"
              # git clone --depth 1 https://github.com/${action_name} external-actions/${action_name}
            fi
            git clone -b ${version} --depth 1 https://github.com/${action_name} external-actions/${action_name}
            rm -r external-actions/${action_name}/.git*
            git add --all
            git commit -m "Cloned ${action_name}@${version}"
            git push --set-upstream origin ${{env.temp_branch}}
            let "actions_cloned++"
          done
          echo "actions_cloned=$actions_cloned" >> $GITHUB_OUTPUT

      - name: Create PR
        if: ${{ steps.run.outputs.actions_cloned > 0 }}
        run: gh pr create --base main --head ${{env.temp_branch}} --title "Merge ${{env.temp_branch}} into main" --fill
        env:
          GH_TOKEN: ${{ github.token }}


