name: Test

on:
  workflow_dispatch:
    inputs:
      test:
        type: string
        

jobs:
    test:
      env:
        TEST: ${{inputs.test}}
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo $TEST
            