name: Test

on:
  workflow_dispatch:
    inputs:
      test:
        type: string
        

jobs:
    test:
      env:
        TEST: ${{inputs.test}}
      runs-on: ubuntu-latest
      steps:
        - run: |
            for element in $TEST; do
              echo $element
            done
    call-reusable-workflow:
      needs: test
      uses: dhong42/insource-actions/.github/workflows/multi-insource.yml@main
      with: 
        actions: atlassian/gajira-login@v2.0.0 aharooms/jira-commenter@v1.0.5 hashicorp/vault-action